version: '3.8'

services:
  # Main evaluation service
  ace-eval:
    build:
      context: .
      dockerfile: Dockerfile
    image: rl-ace-evaluation:latest
    container_name: ace-eval
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount config for easy parameter tuning
      - ./config.yaml:/app/config.yaml:ro
      # Mount results directory for output persistence
      - ./results:/app/results
      - ./logs:/app/logs
    command: python -m ace_task.evaluate --runs 10
    restart: unless-stopped

  # Development service with additional tools
  ace-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: rl-ace-evaluation:dev
    container_name: ace-dev
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: /bin/bash
    stdin_open: true
    tty: true

  # Testing service
  ace-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: rl-ace-evaluation:test
    container_name: ace-test
    volumes:
      - .:/app
    command: pytest tests/ -v --cov=ace_task --cov-report=html
    profiles:
      - test
